spring.application.name=travel-agent
spring.web.cors.allowed-origin-patterns=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*

server.port=9090

google.api.key=

spring.threads.virtual.enabled=true
spring.cloud.gcp.pubsub.enabled=false

resilience4j.retry.instances.geminiRetry.max-attempts=3
resilience4j.retry.instances.geminiRetry.wait-duration=2s
resilience4j.retry.instances.geminiRetry.enable-exponential-backoff=true
resilience4j.retry.instances.geminiRetry.exponential-backoff-multiplier=2
resilience4j.retry.instances.geminiRetry.retry-exceptions=com.google.genai.errors.ClientException


#spring.cloud.gcp.credentials.location=